# Generated by Django 5.1.7 on 2025-05-07 19:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="file",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to=None)),
                ("status", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=255)),
                ("upFile_at", models.DateTimeField(auto_now_add=True)),
                ("is_use", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "File",
            },
        ),
        migrations.CreateModel(
            name="GConc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lstidlaw", models.JSONField(default=list)),
                ("lstConC", models.JSONField(blank=True, default=list, null=True)),
                ("meaning", models.TextField(blank=True, null=True)),
                ("descendants", models.JSONField(blank=True, default=list, null=True)),
                ("updateNeo4j", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="gRel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lstidlaw", models.JSONField(default=list)),
                ("lstRel", models.JSONField(blank=True, default=list, null=True)),
                ("meaning", models.TextField(blank=True, null=True)),
                ("descendants", models.JSONField(blank=True, default=list, null=True)),
                ("lstgConcS", models.JSONField(default=list)),
                ("lstgConcO", models.JSONField(default=list)),
                ("update_concs", models.JSONField(blank=True, default=list, null=True)),
                ("update_conco", models.JSONField(blank=True, default=list, null=True)),
                ("updaterel", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("superadmin", "Super Admin")],
                        default="admin",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employee_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "cccd",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Concele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conC", models.TextField(blank=True, null=True)),
                ("Meaning", models.TextField(blank=True, null=True)),
                ("descendants", models.JSONField(blank=True, default=list, null=True)),
                ("similar", models.IntegerField(blank=True, null=True)),
                (
                    "IdLaw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concele_list",
                        to="api.file",
                    ),
                ),
            ],
            options={
                "db_table": "concele",
            },
        ),
        migrations.CreateModel(
            name="component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent", models.BigIntegerField(blank=True, null=True)),
                ("name", models.TextField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("contentSearch", models.TextField(blank=True, null=True)),
                ("child", models.JSONField(blank=True, default=list, null=True)),
                ("descendants", models.JSONField(blank=True, default=list, null=True)),
                (
                    "is_shorten",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_theory",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "idLaw",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component",
                        to="api.file",
                    ),
                ),
            ],
            options={
                "db_table": "Component",
            },
        ),
        migrations.CreateModel(
            name="Gtext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descendants", models.JSONField(blank=True, default=list, null=True)),
                ("content", models.TextField()),
                ("ConcS", models.CharField(blank=True, max_length=255, null=True)),
                ("Relation", models.CharField(blank=True, max_length=255, null=True)),
                ("ConcO", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "idLaw",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component",
                        to="api.file",
                    ),
                ),
            ],
            options={
                "db_table": "gtext",
            },
        ),
        migrations.CreateModel(
            name="relEle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation", models.TextField(max_length=255)),
                ("Meaning", models.TextField(blank=True, null=True)),
                ("descendants", models.JSONField(blank=True, default=list, null=True)),
                ("similar", models.IntegerField(blank=True, null=True)),
                (
                    "IdLaw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concele_list",
                        to="api.file",
                    ),
                ),
                (
                    "concO",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concele_list",
                        to="api.concele",
                    ),
                ),
                (
                    "concS",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concele_list",
                        to="api.concele",
                    ),
                ),
            ],
            options={
                "db_table": "relele",
            },
        ),
        migrations.CreateModel(
            name="SuggestConc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conc1", models.TextField()),
                ("conc2", models.TextField()),
                ("similar_index", models.FloatField()),
                (
                    "id1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_from",
                        to="api.concele",
                    ),
                ),
                (
                    "id2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_to",
                        to="api.concele",
                    ),
                ),
            ],
            options={
                "db_table": "suggestconc",
                "unique_together": {("id1", "id2")},
            },
        ),
        migrations.CreateModel(
            name="SuggestRel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation1", models.TextField()),
                ("relation2", models.TextField()),
                ("similar_index", models.FloatField()),
                (
                    "id1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rel_suggest_from",
                        to="api.relele",
                    ),
                ),
                (
                    "id2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rel_suggest_to",
                        to="api.relele",
                    ),
                ),
            ],
            options={
                "db_table": "suggestrel",
                "unique_together": {("id1", "id2")},
            },
        ),
    ]
