<<<<<<< Updated upstream
# Generated by Django 5.1.7 on 2025-03-18 23:03

=======
# Generated by Django 5.1.7 on 2025-04-19 02:47

import django.db.models.deletion
>>>>>>> Stashed changes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
<<<<<<< Updated upstream
            name="UpFile",
=======
            name="file",
>>>>>>> Stashed changes
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to=None)),
<<<<<<< Updated upstream
                ("Status", models.IntegerField(default=1)),
                ("Name", models.CharField(max_length=255)),
                ("upFile_at", models.DateTimeField(auto_now_add=True)),
=======
                ("status", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=255)),
                ("upFile_at", models.DateTimeField(auto_now_add=True)),
                ("is_use", models.BooleanField(default=False)),
>>>>>>> Stashed changes
            ],
            options={
                "db_table": "File",
            },
        ),
<<<<<<< Updated upstream
=======
        migrations.CreateModel(
            name="GConc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lstidlaw", models.JSONField(default=list)),
                ("lstConC", models.JSONField(blank=True, default=list, null=True)),
                ("meaning", models.TextField(blank=True, null=True)),
                ("descendants", models.JSONField(blank=True, default=list, null=True)),
                ("updateNeo4j", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="gRel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lstidlaw", models.JSONField(default=list)),
                ("lstRel", models.JSONField(blank=True, default=list, null=True)),
                ("meaning", models.TextField(blank=True, null=True)),
                ("descendants", models.JSONField(blank=True, default=list, null=True)),
                ("lstgConcS", models.JSONField(default=list)),
                ("lstgConcO", models.JSONField(default=list)),
                ("update_concs", models.JSONField(blank=True, default=list, null=True)),
                ("update_conco", models.JSONField(blank=True, default=list, null=True)),
                ("updaterel", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Concele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conC", models.TextField(blank=True, null=True)),
                ("Meaning", models.TextField(blank=True, null=True)),
                ("descendants", models.JSONField(blank=True, default=list, null=True)),
                ("similar", models.IntegerField(blank=True, null=True)),
                (
                    "IdLaw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concele_list",
                        to="api.file",
                    ),
                ),
            ],
            options={
                "db_table": "concele",
            },
        ),
        migrations.CreateModel(
            name="component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent", models.BigIntegerField(blank=True, null=True)),
                ("name", models.TextField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("contentSearch", models.TextField(blank=True, null=True)),
                ("child", models.JSONField(blank=True, default=list, null=True)),
                ("descendants", models.JSONField(blank=True, default=list, null=True)),
                (
                    "is_shorten",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_theory",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "idLaw",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component",
                        to="api.file",
                    ),
                ),
            ],
            options={
                "db_table": "Component",
            },
        ),
        migrations.CreateModel(
            name="Gtext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descendants", models.JSONField(blank=True, default=list, null=True)),
                ("content", models.TextField()),
                ("ConcS", models.CharField(blank=True, max_length=255, null=True)),
                ("Relation", models.CharField(blank=True, max_length=255, null=True)),
                ("ConcO", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "idLaw",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component",
                        to="api.file",
                    ),
                ),
            ],
            options={
                "db_table": "gtext",
            },
        ),
        migrations.CreateModel(
            name="relEle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation", models.TextField(max_length=255)),
                ("Meaning", models.TextField(blank=True, null=True)),
                ("descendants", models.JSONField(blank=True, default=list, null=True)),
                ("similar", models.IntegerField(blank=True, null=True)),
                (
                    "IdLaw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concele_list",
                        to="api.file",
                    ),
                ),
                (
                    "concO",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concele_list",
                        to="api.concele",
                    ),
                ),
                (
                    "concS",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concele_list",
                        to="api.concele",
                    ),
                ),
            ],
            options={
                "db_table": "relele",
            },
        ),
        migrations.CreateModel(
            name="SuggestConc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conc1", models.TextField()),
                ("conc2", models.TextField()),
                ("similar_index", models.IntegerField()),
                (
                    "id1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_from",
                        to="api.concele",
                    ),
                ),
                (
                    "id2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_to",
                        to="api.concele",
                    ),
                ),
            ],
            options={
                "db_table": "suggestconc",
                "unique_together": {("id1", "id2")},
            },
        ),
        migrations.CreateModel(
            name="SuggestRel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation1", models.TextField()),
                ("relation2", models.TextField()),
                ("similar_index", models.IntegerField()),
                (
                    "id1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rel_suggest_from",
                        to="api.relele",
                    ),
                ),
                (
                    "id2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rel_suggest_to",
                        to="api.relele",
                    ),
                ),
            ],
            options={
                "db_table": "suggestrel",
                "unique_together": {("id1", "id2")},
            },
        ),
>>>>>>> Stashed changes
    ]
